version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: hexagon-mysql
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - 3303:3306
    environment:
      - MYSQL_DATABASE=hexagon
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect=SET NAMES utf8
      - --default_time_zone=+09:00
      - --explicit_defaults_for_timestamp
  redis:
    image: redis:5.0.7-alpine
    container_name: hexagon-redis
    ports:
      - 6399:6379
    volumes:
      - ./redis:/data
    restart: always
  mongodb:
    image: mongo
    container_name: hexagon-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=hexagon
