version: '3.7'

volumes:
  data:
    driver: local
  config:
    driver: local

services:
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    restart: always